import type { Metadata } from "next";
import { site } from "./site";

/** Static share image (public/og.png, generated by scripts/generate-brand-images.mjs). */
export const OG_IMAGE = {
  url: "/og.png",
  width: 1200,
  height: 630,
  alt: "Alfapoint: senior engineers for products that need to ship",
};

type PageMetaInput = { path: string; title?: string; description?: string };

/**
 * Per-page metadata. Next.js replaces `openGraph` wholesale when a page sets it,
 * so canonical and og:url are always derived together from the same path.
 */
export function pageMetadata({ path, title, description = site.description }: PageMetaInput): Metadata {
  const ogTitle = title ? `${title} | ${site.name}` : `${site.name}: ${site.tagline}`;
  return {
    ...(title ? { title } : {}),
    description,
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      siteName: site.name,
      title: ogTitle,
      description,
      url: path,
      // Pages replace the parent's openGraph wholesale, so the image must be set here too
      images: [OG_IMAGE],
    },
  };
}
